server:
  port: 8081
  
logging:
  config: classpath:logback.xml
  
zookeeper:
  servers: 10.0.202.63:2181,10.0.202.63:2182
  namespace: gateway/aggregator
  
aggregator:
  request: nettyAggregatorRequest